AY2425S1-CS2103T-T13-4/tp

docs/AboutUs.md

Add profile photo

---

docs/AboutUs.md

Update AboutUs.md to include Pradyumna Prasad

---

docs/DeveloperGuide.md

This pull request updates the `DeveloperGuide.md` with new sections for user stories, use cases, non-functional requirements, and a glossary to improve clarity and developer understanding.
1. **User Profile and Stories**:
- Defined the target user as independent Geriatricians managing elderly patients.
- Added a value proposition explaining how CareLink addresses the specific needs of Geriatricians.
- Included user stories for various stages of the user experience:
- First use (new user)
- Second use (regular user)
- Tenth use (novice user)
- Hundredth use (experienced user)
- Marked specific user stories for MVP and final versions.
2. **Use Cases**:
- Added **Use Case 01** for adding a new patient:
- Preconditions, guarantees, main success scenario, and extensions for adding a patient to …

Update Developer Guide with Use Cases, NFRs, User Stories, and Glossary

---

docs/_config.yml

Remove traces of AB3 from config file

Update config.yml file

---

docs/DeveloperGuide.md

Reformat DG to meet AB3 format in Appendix

Fix errors in Developer Guide

---

docs/index.md

Update index page with CareLink introduction

Replace all mentions of AB3 with CareLink in docs/index.md

---

src/main/java/seedu/address/model/person/Nric.java
src/main/java/seedu/address/model/person/Person.java

Update Person Model to include NRIC

---

src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

update storage for tests

---

src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Update testutil module to comply with new nric field. Fixes #69.

Update testutil for tests

---

src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Update logic for tests

---

docs/AboutUs.md
docs/UserGuide.md
docs/team/ponharish.md
docs/team/suhayl13.md
src/main/java/seedu/address/logic/commands/FindNricCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FindNricCommandParser.java
src/main/java/seedu/address/model/person/Nric.java
src/main/java/seedu/address/model/person/NricContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FindNricCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindNricCommandParserTest.java

Feature: Find Person

---

src/main/java/seedu/address/logic/commands/AddCommand.java

Update message usage to show correct message

---

src/main/java/seedu/address/logic/commands/LinkCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/LinkCommandTest.java

Add link command and associated methods to add new links and check for links
Associated with #72

Add link command and associated methods to add new links and check for links

---

.vscode/settings.json
build.gradle
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/LinkCommand.java
src/test/java/seedu/address/logic/parser/LinkCommandParserTest.java

- Change example add message to have valid NRIC
- Amend response after add to indicate role

Fix minor errors

---

src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
src/main/java/seedu/address/logic/commands/LinkCommand.java
src/test/java/seedu/address/logic/commands/DeleteLinkCommandTest.java

Fix #105 
Parser not implemented yet. But command has been implemented and thoroughly tested.

Add delete link command (without parser)

---

src/main/java/seedu/address/model/person/Note.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedNote.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/storage/JsonAdaptedNoteTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

This PR introduces functionality to manage notes within `Person` objects, along with necessary updates to serialization and deserialization methods to include these notes. The changes follow the established patterns for JSON adaptation in the project, ensuring that notes can be stored and retrieved seamlessly in JSON format. This feature enables doctors (or users of the system) to store relevant notes for individuals. Related to #102 
1. **Create `Note` Class**:
- Introduced a `Note` class to allow the storage of notes for each person.
- Added necessary documentation for the class.
2. **Add Notes to `Person` Class**:
- Added a `List<Note>` field in `Person` to manage multiple notes.
- Implemented `addNote()` method to add notes to a `Person`.
- Implemented `getNotes()` method to retrieve …

Add Notes Functionality to Person Class and Update JSON Serialization

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FindCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/test/java/seedu/address/logic/commands/CommandResultTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/HelpCommandTest.java

Fixes #124 
The constructor of CommandResult class has been modified to accommodate the new method isFind().
This method will be useful to render the relevant UI when we find a person

update Constructor of CommandResult class

---

docs/diagrams/UiClassDiagram.puml

This PR is set to merge into `107-update-dg-to-add-uml-commands` branch

Update UML diagram of UI component

---

docs/diagrams/ModelClassDiagram.puml

- Added new classes: Appointment, Note, and Role to the UML diagram to reflect the expanded model structure.
- Updated relationships:
- Person now has many-to-one relationships with Appointment, Note, Role, and Tag.
- Ensured adherence to previous diagram style and structure.
- Adjusted package Model to include newly introduced entities and their relations.
Related to #107

update UML diagram for extended model components

---

build.gradle
src/main/java/seedu/address/logic/parser/FindCommandParser.java

Also added "enable assertions" in build.gradle file.

Add logging to FindCommandParser

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditAppointmentParser.java
src/main/java/seedu/address/model/AppointmentManager.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/appointment/Appointment.java
src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java

- Add edit appointment
Related to https://github.com/AY2425S1-CS2103T-T13-4/tp/issues/111

Add edit appointment feature

---

src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Fixed the jsonadaptedperson to parse and store the data for link correctly
Fixes #151

fix json parser to not break for link command

---

src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditAppointmentParser.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java

- Change the command from `editapp findnric/S1234567D finddate/20/10/2025 findstart/10:00 nric/S1234567D d/20/10/2025 start/11:00 end/12:00` to `editapp nric/S1234567D d/20/10/2025 start/10:00 newd/20/10/2025 newstart/11:00 newend/12:00`
-  Add checks for invalid start time or end time (ie. reject end time later than start time, reject start time before current time)
- #160

Update cli syntax for edit appointment command

---

src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

This pull request enhances the `TypicalPersons` class to include more comprehensive attributes for each `Person` object. The updates include:
- **Appointments**: Added sample `Appointment` objects for each `Person`.
- **Caregivers & Patients**: Established relationships between caregivers and their patients using the `caregivers` and `patients` fields.
- **Notes**: Added detailed `notes` for follow-up actions or reminders.
- **TypicalPersonsAddressbook.json**: Changed the JSON file to include new fields added for Person class.
1. **Appointments**:
- Each `Person` object that requires scheduling now has an `appointments` field.
- Sample `Appointment` objects have been created with relevant `startTime` and `endTime`.
2. **Caregivers & Patients Relationships**:
- Specified which `Person` …

Update typical person address book to contain new fields

---

src/main/java/seedu/address/ui/HelpWindow.java

Update user guide link with new link

---

docs/DeveloperGuide.md

Update dg for edit appointment

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Update Edit command to handle personNotFound

---

src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java

Fix EditAppointment Command

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Update prompt in EditCommand

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java

Fixes #185 
Fixes #186 
Changes in this PR

Add Command Prompt and Command Result

---

src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java

Update Delete Appointment Command Prompt

---

src/main/java/seedu/address/logic/commands/LinkCommand.java
src/test/java/seedu/address/logic/commands/LinkCommandTest.java

Update link command error to be more meaningful for incorrect NRIC

---

src/main/java/seedu/address/logic/commands/LinkCommand.java

Update NRIC in link command example to be valid

---

src/main/java/seedu/address/model/person/UniquePersonList.java

Update to allow cross linking of dual roles

---

src/main/java/seedu/address/logic/parser/AddAppointmentParser.java
src/main/java/seedu/address/logic/parser/DeleteAppointmentParser.java
src/main/java/seedu/address/logic/parser/EditAppointmentParser.java
src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/DeleteAppointmentCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java

Fixes #196 
Fixes #200 
Fixes #201

Update preamble messages for appointments

---

src/main/java/seedu/address/logic/commands/LinkCommand.java

Update link command to check for same person correctly

---

src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteAppointmentParser.java

Verify no duplicate prefixed for notes and delete appointment

---

src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
src/main/java/seedu/address/model/AppointmentManager.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java

Update edit appointment to correctly handle duplicates

---

src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java

Fix edit appointment issues

---

src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java

Fix nric issues in examples

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

-caregiver and patient links should remain after editing

190 edit command removes the existing link that the edited person

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java

- Remove redundant functions from delete appointment command

Remove redundant functions

---

docs/UserGuide.md

Update ug for update status command

Update ug for update status command

---

docs/_sass/minima/_base.scss

attempt to fix #247

---

docs/UserGuide.md

- fix #287 - Error message showing incorrect
- fix #291 - Find shows many users and I need to use mouse
- fix #293 - Cannot see fully the prompt (closes previous issue as well)
- fix #300 - Appointment Start and End times
- fix #301 - Duplicate Emails are allowed
- fix #304 - Error message specificity

Fix ug part 3

---

docs/DeveloperGuide.md
docs/diagrams/ClearConfirmSequenceDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Fixes #251.
Fixes #255.
Fixes #257.
Fixes #258.
Fixes #261.
Fixes #264.
Fixes #266.

Fix multiple bugs in the DG

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/diagrams/ArchitectureSequenceDiagram.puml

Fix #325 
Fix #318 
Fix #315
Fix #314 
Fix #312

Fix dg issues

---

docs/UserGuide.md
docs/_config.yml

Final-UG-fix

---

docs/UserGuide.md

- Change UG title to CareLink User Guide
- Remove duplicate User Guide title

Update ug title

---

docs/DeveloperGuide.md

Add use case for update status

---

docs/UserGuide.md

Add warning for case insensitive tags

---

docs/UserGuide.md

Add a way to check for java version in UG

---

docs/UserGuide.md

Fixed some typos and inconsistencies in the UG.

Fix errors in the UG

---

docs/UserGuide.md

Add workaround for relink in edit

---

docs/UserGuide.md

Fix #371 
Fix some other minor inconsistencies and sample commands

Fix more and more ug bugs

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update Dg to include planned enhancements

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/test/java/seedu/address/model/person/ContainsKeywordsPredicateTest.java

Fix more bugs in UG and Dg. Added Planed Enhancement and Known issues to Dg and UG respectively. Removed dead code from ContainsKeywordPredicateTest.

Fix more bugs in UG and DG

---

docs/DeveloperGuide.md

update formatting for dg
